[project]
name = "django-orm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.8",
    "django-bootstrap5>=26.1",
    "django-debug-toolbar>=6.1.0",
    "faker>=38.2.0",
]
